### ISSUE TITLE
increase refresh time

### ISSUE THREAD

**Issue by jackflem1** [corinuss/Hubitat_IntelliFire#1]
I'm try to increase the refresh times and getting this error..

log.info "Increasing refresh frequency to every 15 minutes while fireplace is on."
                runEvery15Minutes("refresh")
            }
            else
            {
                log.info "Decreasing refresh frequency to every 45 Minutes while fireplace is off."
                runEvery45Minutes("refresh")

groovy.lang.MissingMethodException: No signature of method: user_driver_IntelliFire_IntelliFire_Fireplace_820.runEvery45Minutes() is applicable for argument types: (java.lang.String) values: [refresh] on line 222 (method refresh)

Reason for increasing the time is I believe there is a problem with the wifi unit that over time the polling causes the response to slow and then eventually hang the unit. I would like the refresh when off to be in Hours. I tried runevery2Hours and got the same error.

**Comment by corinuss** [comment]
That's a built-in Hubitat function, so you need to choose one of the valid intervals.  See this page (near the bottom) for the list of functions.
[https://docs2.hubitat.com/en/developer/common-methods-object](https://docs2.hubitat.com/en/developer/common-methods-object) 

If one of those intervals doesn't work for you, you could also use runIn(), but you'll need to add another runIn call at the bottom of the refresh function to keep the cycle going.

Edit - Actually, I'm not sure if runIn() automatically repeats or not, since there's also a runOnce().  You may have to experiment here.

**Comment by jackflem1** [comment]
Thanks for the quick reply, all set now!

**Comment by jackflem1** [comment]
closing
